'use client';
import { useEffect,useMemo,useState } from 'react';
import { HomeHero } from '@/components/home/HomeHero';import { MethodSummary } from '@/components/home/MethodSummary';import { QuizShell } from '@/components/quiz/QuizShell';import { ChapterTransition } from '@/components/quiz/ChapterTransition';import { ResultView } from '@/components/result/ResultView';import { AboutDialog } from '@/components/AboutDialog';
import { chapterCopy,questions } from '@/data/questions';import { createResult } from '@/lib/matching';import { clearSaved,loadProgress,PROGRESS_KEY,RESULT_KEY,saveProgress,VERSION } from '@/lib/storage';import type { Answers } from '@/types/quiz';
type Mode='home'|'chapter'|'quiz'|'result';
export default function Home(){const [mode,setMode]=useState<Mode>('home');const [index,setIndex]=useState(0);const [answers,setAnswers]=useState<Answers>({});const [about,setAbout]=useState(false);const result=useMemo(()=>Object.keys(answers).length===32?createResult(answers):null,[answers]);
 useEffect(()=>{const saved=loadProgress();if(saved){setAnswers(saved.answers);const i=questions.findIndex(q=>q.id===saved.currentQuestionId);setIndex(i<0?0:i)}try{const s=JSON.parse(localStorage.getItem(RESULT_KEY)||'null');if(s?.questionSetVersion===VERSION&&s.answers&&Object.keys(s.answers).length===32){setAnswers(s.answers);setMode('result')}}catch{}},[]);
 const start=()=>{setMode(index%8===0?'chapter':'quiz')};const choose=(id:string)=>{const next={...answers,[questions[index].id]:id};setAnswers(next);saveProgress(questions[index].id,next)};
 const next=()=>{if(!answers[questions[index].id])return;if(index===31){localStorage.setItem(RESULT_KEY,JSON.stringify({questionSetVersion:VERSION,answers,generatedAt:new Date().toISOString()}));setMode('result');return}const n=index+1;setIndex(n);saveProgress(questions[n].id,answers);setMode(n%8===0?'chapter':'quiz')};
 const previous=()=>{if(index>0){setIndex(index-1);setMode('quiz')}};const exit=()=>setMode('home');const restart=()=>{if(confirm('重新测试会清除当前答案和结果，确定继续吗？')){clearSaved();setAnswers({});setIndex(0);setMode('home')}};
 return <>{mode==='home'&&<main className="home-page"><HomeHero onStart={start} hasProgress={Object.keys(answers).length>0&&Object.keys(answers).length<32} onAbout={()=>setAbout(true)}/><MethodSummary/><footer className="site-footer"><span>诗心鉴 · 2026</span><button onClick={()=>setAbout(true)}>方法与边界</button></footer></main>}{mode==='chapter'&&<ChapterTransition chapter={chapterCopy[Math.floor(index/8)]} onContinue={()=>setMode('quiz')}/>} {mode==='quiz'&&<QuizShell index={index} answers={answers} onChoose={choose} onPrevious={previous} onNext={next} onExit={exit}/>} {mode==='result'&&result&&<ResultView result={result} answers={answers} onRestart={restart} onBack={()=>setMode('quiz')} onAbout={()=>setAbout(true)}/>} {about&&<AboutDialog onClose={()=>setAbout(false)}/>}</>}
